package br.com.liviacare.worm.query;

import java.util.Objects;

/**
 * Represents pagination and sorting for a query.
 * This record replaces the need for a separate Pageable interface and PageRequest class.
 *
 * @param pageNumber The page number (0-based).
 * @param pageSize   The page size.
 * @param sort       The sort instruction to apply.
 */
public record Pageable(int pageNumber, int pageSize, Sort sort) {

    /**
     * Enum for sort direction.
     */
    public enum Direction {
        ASC, DESC
    }

    /**
     * Represents a single sort instruction.
     *
     * @param property  The property to sort by.
     * @param direction The sort direction (ASC or DESC).
     */
    public record Sort(String property, Direction direction) {
        public static Sort by(String property, Direction direction) {
            return new Sort(property, direction == null ? Direction.ASC : direction);
        }

        public static Sort asc(String property) {
            return by(property, Direction.ASC);
        }

        public static Sort desc(String property) {
            return by(property, Direction.DESC);
        }
    }

    // Factory methods for Pageable

    public static Pageable of(int pageNumber, int pageSize) {
        return of(pageNumber, pageSize, null);
    }

    public static Pageable of(int pageNumber, int pageSize, Sort sort) {
        int p = Math.max(0, pageNumber);
        int s = Math.max(1, pageSize);
        // Defaults to sort by id ascending when no sort is provided.
        return new Pageable(p, s, sort == null ? Sort.asc("id") : sort);
    }

    public static Pageable ofSize(int pageSize) {
        return of(0, pageSize, null);
    }

    // Canonical constructor for validation
    public Pageable {
        Objects.requireNonNull(sort, "Sort must not be null.");
    }

    // Public getters (generated by record)

    public long getOffset() {
        return (long) pageNumber * pageSize;
    }
}
